# list targets
default:
    @just --list

# build bin.cpp with g++
bin:
    g++ bin.cpp -Wall -Wextra -pedantic -o bin -O2 -m64

# build diff.cpp with g++
diff:
    g++ diff.cpp -Wall -Wextra -pedantic -o diff -O2 -m64
