[package]
name = "ws-scrape"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
futures-util = "0.3"
reqwest = "0.11"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
websocket = "0.24"
