[package]
name = "download"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
flate2 = "1.0"
futures = "0.3"
reqwest = { version = "0.11.10" }
tar = "0.4"
tokio = { version = "1", features = ["full"] }
